
## hugo config file for inVisement static website (mainly blog)
## to run: hugo (server) --config config/hugoConfig.toml

baseURL = "https://invisement.com/"
languageCode = "en-us"
title = "inVisement"
themesDir = "hugo-themes"
theme = "inVisement"
#disqusShortname = "clientrelationship" # delete this to disable disqus comments
googleAnalytics = "UA-123665575-1"
publishDir = ".invisement.com"
uglyurls = true
#disableKinds = ["home"]

## to format code blocks
pygmentsCodefences = true
pygmentsStyle = "dracula"

#pygmentsUseClassic = false
#pygmentsUseClasses = false
#pygmentsCodefencesGuessSyntax = true
#linenos = "table"


[taxonomies]
#    tag = "tags"

[params]
    author = "inVisement"
    githubUsername = "inVisement"
    accent = "coral"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts! like Stylish, Lato, Roboto, Sunflower, Raleway

[[menu.main]]
    url = "https://data.invisement.com?q-stmt/AAPL.csv"
    name = "Explore Datasets"
    weight = 10

[[menu.main]]
    url = "/market-view.html"
    name = "Market View"
    weight = 15

[[menu.main]]
    url = "/risk-analysis.html"
    name = "Risk Analysis"
    weight = 16

[[menu.main]]
    url = "/invisement-portfolio.html"
    name = "Portfolio"
    weight = 17

[[menu.main]]
    url = "/api-doc.html"
    name = "API Doc"
    weight = 20

[[menu.main]]
    url = "/blogs.html"
    name = "Blogs"
    weight = 30

[[menu.main]]
    url = "/about.html"
    name = "About us"
    weight = 40

#[[menu.main]]
#    url = "/tags/"
#    name = "tags"
#    weight = 50


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:client@invisement.com"
    name = "envelope-o"
    weight = 10

[[menu.icon]]
    url = "https://github.com/inVisement/"
    name = "github"
    weight = 20
